---
output: pdf_document
header-includes:
   - \usepackage{caption}
   - \captionsetup[table]{labelformat=empty}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE)
```
\pagenumbering{gobble}
\captionsetup{width=9in}

```{r}
# load environmental variables ------------------------------------------------

source("./0-config.R")

gl_run_date <- '2024-04-14'

```

```{r}
library(tidyverse)
library(kableExtra)
```

```{r}
#read in data
bird_df <- readRDS(paste0(dir, 'Results/bird-gl-phylo-vint-', gl_run_date, 
               '/bird-gl-phylo-vint-data-', gl_run_date, '.rds'))$pro_data %>%
  dplyr::arrange(species) %>%
  dplyr::mutate('Scientific Name' = gsub('_', ' ', species),
                GL = round(exp(lGL), 1),
                Mass = round(exp(lMass), 0),
                temp_sd_year = round(temp_sd_year, 2),
                precip_cv_year = round(precip_cv_year, 2),
                temp_sd_season = round(temp_sd_season, 2),
                precip_cv_season = round(precip_cv_season, 2),
                temp_delta = round(temp_delta, 2),
                precip_delta = round(precip_delta, 2)) %>%
  dplyr::relocate('Scientific Name', .before = ID) %>%
  dplyr::relocate('Family', .before = Order) %>%
  dplyr::relocate('precip_cv_year', .after = temp_sd_year) %>%
  dplyr::relocate('precip_cv_season', .after = temp_sd_season) %>%
  dplyr::relocate('GL', .after = lGL) %>%
  dplyr::relocate('Mass', .after = lMass) %>%
  dplyr::rename('G (y)' = GL,
                'Niche' = Trophic_niche,
                'Mass (g)' = Mass,
                '$\\tau_{inter_{T}}$' = temp_sd_year,
                '$\\tau_{inter_{P}}$' = precip_cv_year,
                '$\\tau_{intra_{T}}$' = temp_sd_season,
                '$\\tau_{intra_{P}}$' = precip_cv_season,
                '$\\delta_{T}$' = temp_delta,
                '$\\delta_{P}$' = precip_delta) %>%
  dplyr::select(-ID, -species, -niche_idx, -lGL, -lMass, -Order)

# write.csv(bird_df, paste0(dir, "/data/L3/bird_table_s1.csv"))
  
```

```{r}
col_idx <- seq(1, NROW(bird_df), by = 2)

kableExtra::kbl(bird_df, format = 'latex', booktabs = TRUE, longtable = TRUE, 
                align = 'c',
                caption = '\\textit{Table S1}: For all species considered in this study, the scientific species name, family, generation length (G) in years, trophic niche category, mass, inter-annaual variation in temperature ($\\tau_{inter_{T}}$), inter-annaual variation in precipitation ($\\tau_{inter_{P}}$), intra-annaual variation in temperature ($\\tau_{intra_{T}}$), intra-annaual variation in precipitation ($\\tau_{intra_{P}}$), rates of temperature change in terms of standard deviations per generation ($\\delta_{T}$), rate of precipitation change in terms of standard deviations per generation ($\\delta_{P}$).',
                  # col.names = c('Species','$\\omega_{M_{TIME}}$', '$\\omega_{M_{LAT}}$', '$\\omega_{M_{ELEV}}$', 
                  #   '$\\omega_{W_{TIME}}$', '$\\omega_{W_{LAT}}$', '$\\omega_{W_{ELEV}}$'),
                escape = FALSE) %>% 
  kableExtra::column_spec(column = 1, italic = TRUE) %>% 
  #kableExtra::column_spec(column = 5:7, width = '0.75in', latex_valign = 'm') %>% 
  kableExtra::kable_styling(latex_options = 'repeat_header', 
                                 full_width = FALSE) %>%
  kableExtra::row_spec(col_idx, color = "black", background = "lightgray") %>%
  kableExtra::landscape()
```
