#!/bin/bash
n="extractSpecies" # job name

# Note that 110 is the number of pieces the BL IDs were split up into. 
# Should probably not hardcode this...
for i in {1..110}
do
  sbatch --job-name=$n --output=$n.$i.SLURMout --export=fileName=BLIDsPiece-$i.rda extract.sbatch
done
